package crypto

import (
	"errors"
	"fmt"

	"github.com/open-quantum-safe/liboqs-go/oqs"
)

// KemEncapsulation pairs a KEM ciphertext with the corresponding shared
// secret. Both fields are byte-for-byte the same as the upstream liboqs
// outputs.
type KemEncapsulation struct {
	Ciphertext   []byte
	SharedSecret []byte
}

// KemKeyPair is the result of KEM keygen.
type KemKeyPair struct {
	PublicKey []byte
	SecretKey []byte
}

// Kem is a wrapper around liboqs-go's *oqs.KeyEncapsulation that exposes
// the canonical QNSP API surface (Keygen / Encapsulate / Decapsulate)
// regardless of which liboqs candidate name is selected internally.
type Kem struct {
	algName     string  // canonical QNSP name
	internalAlg string  // liboqs candidate name actually used
	encap       oqs.KeyEncapsulation
	initialized bool
}

// NewKem constructs a KEM for the given canonical QNSP algorithm name.
// The caller must Close the returned Kem when finished.
//
// Returns an error if the algorithm is unknown to QNSP or if no
// liboqs-enabled candidate matches.
func NewKem(algorithm string) (*Kem, error) {
	candidates, ok := kemCandidates[algorithm]
	if !ok {
		return nil, fmt.Errorf("qnsp/crypto: unknown KEM algorithm %q (call SupportedKEMs to enumerate)", algorithm)
	}
	for _, candidate := range candidates {
		if oqs.IsKEMEnabled(candidate) {
			k := &Kem{algName: algorithm, internalAlg: candidate}
			if err := k.encap.Init(candidate, nil); err != nil {
				return nil, fmt.Errorf("qnsp/crypto: liboqs init failed for %q: %w", candidate, err)
			}
			k.initialized = true
			return k, nil
		}
	}
	return nil, fmt.Errorf("qnsp/crypto: KEM %q not enabled in this liboqs build (tried %v)", algorithm, candidates)
}

// Algorithm returns the canonical QNSP algorithm name passed to NewKem.
func (k *Kem) Algorithm() string { return k.algName }

// LibOQSName returns the underlying liboqs candidate name being used.
func (k *Kem) LibOQSName() string { return k.internalAlg }

// Keygen produces a public/secret key pair. The secret-key bytes are
// returned for portability with the rest of the QNSP SDK family; if you
// only need to use the same Kem instance for one decapsulation, the
// upstream liboqs binding also retains the secret key internally.
func (k *Kem) Keygen() (KemKeyPair, error) {
	if !k.initialized {
		return KemKeyPair{}, errors.New("qnsp/crypto: Kem not initialized")
	}
	pk, err := k.encap.GenerateKeyPair()
	if err != nil {
		return KemKeyPair{}, fmt.Errorf("qnsp/crypto: keygen: %w", err)
	}
	sk := k.encap.ExportSecretKey()
	skCopy := append([]byte(nil), sk...)
	return KemKeyPair{PublicKey: pk, SecretKey: skCopy}, nil
}

// Encapsulate runs encapsulation against the supplied public key.
func (k *Kem) Encapsulate(publicKey []byte) (KemEncapsulation, error) {
	if !k.initialized {
		return KemEncapsulation{}, errors.New("qnsp/crypto: Kem not initialized")
	}
	ct, ss, err := k.encap.EncapSecret(publicKey)
	if err != nil {
		return KemEncapsulation{}, fmt.Errorf("qnsp/crypto: encapsulate: %w", err)
	}
	return KemEncapsulation{Ciphertext: ct, SharedSecret: ss}, nil
}

// Decapsulate runs decapsulation. The supplied secret key must be the
// secret key returned by Keygen on a Kem of the same algorithm.
//
// liboqs-go binds the secret key inside the *oqs.KeyEncapsulation
// instance, so we instantiate a fresh KEM bound to `secretKey` here to
// allow the caller to decapsulate with a key that was generated by a
// different Kem instance (e.g. one loaded from storage).
func (k *Kem) Decapsulate(ciphertext, secretKey []byte) ([]byte, error) {
	var fresh oqs.KeyEncapsulation
	if err := fresh.Init(k.internalAlg, secretKey); err != nil {
		return nil, fmt.Errorf("qnsp/crypto: rebind kem for decap: %w", err)
	}
	defer fresh.Clean()
	ss, err := fresh.DecapSecret(ciphertext)
	if err != nil {
		return nil, fmt.Errorf("qnsp/crypto: decapsulate: %w", err)
	}
	return ss, nil
}

// Close releases the underlying liboqs resources. After Close, the Kem
// must not be used.
func (k *Kem) Close() {
	if k.initialized {
		k.encap.Clean()
		k.initialized = false
	}
}
